### ISSUE TITLE
win11 权限问题 - 8000端口占用 - 酷狗服务占用的 - 关闭酷狗即可 - 已解决

### ISSUE THREAD

**Issue by pengchenggang** [bosichong/MiniAdmin#1]
![image](https://user-images.githubusercontent.com/7833742/217489639-ae477aca-0c48-4743-b776-043223272d27.png)
INFO:     Will watch for changes in these directories: ['E:\\githubz\\MiniAdmin-master\\back']
ERROR:    [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

**Comment by bosichong** [comment]
WinError 10013 你可以搜一下这个错误代码，一般是端口占用，或是账户权限不足等原因造成的。

**Comment by pengchenggang** [comment]
![image](https://user-images.githubusercontent.com/7833742/217683726-67c09c43-44c3-434c-b8a9-a003fcb4eb64.png)
解决了，是8000端口被酷狗音乐server占用了，昨天下班差5分钟刷到你这个，所以就试了试，由于时间比较紧，截个图，就下班跑路了。

另外差个杀酷狗进程没有用，这个进程会自动复苏，然后8000端口还是会被占用，我把酷狗右键给关闭了，就起来了，建议你可以换个别的默认端口。
